spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/fullstack_example_draft}
    username: ${DB_USERNAME:root}
    # password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
